dj2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from music import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

# urlpatterns += [
#     path('', views.index, name='index')
# ]

urlpatterns += [
    path('music/', include('music.urls'))
]

urlpatterns += [
    path('', RedirectView.as_view(url='music/'))
]



# ''
# 'music/'
# 'bands/'

music/urls.py
"""URL Configs of the music app.
"""
from django.http import HttpResponse
from django.urls import path

from music import views

# urlpatterns = [
#     path('', views.index, name='index')
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

urlpatterns += [
    path('bands/', views.BandListView.as_view(), name='band-list'),
    path('bands/<int:pk>/', views.BandDetailView.as_view(), name='band-detail'),
    path('bands/create/', views.BandCreateView.as_view(), name='band-create'),
    path('bands/update/<int:pk>/', views.BandUpdateView.as_view(), name='band-update'),
    path('bands/delete/<int:pk>/', views.BandDeleteView.as_view(), name='band-delete'),
]

urlpatterns += [
    path('musicians/', views.MusicianListView.as_view(), name='musician-list'),
    path('musicians/<int:pk>/', views.MusicianDetailView.as_view(), name='musician-detail'),
    path('musicians/create/', views.MusicianCreateView.as_view(), name='musician-create'),
    path('musicians/update/<int:pk>/', views.MusicianUpdateView.as_view(), name='musician-update'),
    path('musicians/delete/<int:pk>/', views.MusicianDeleteView.as_view(), name='musician-delete'),
]

music/models.py
from django.db import models

# Create your models here.
from django.db.models import CharField, IntegerField, ForeignKey, DateField, BooleanField
from django.urls import reverse


class Band(models.Model):

    name = CharField(max_length=50, default='unknown')
    country = CharField(max_length=50, default='unknown')
    start = IntegerField(blank=True, null=True, verbose_name='The year when the band started performing together')
    end = IntegerField(blank=True, null=True, verbose_name='The year when the band stopped performing together')

    def __str__(self):
        name_str = f'{self.name} '
        country_str = f'({self.country}), '
        start_str = f'{self.start}-' if self.start else '...-'
        end_str = f'{self.end}' if self.end else '...'
        return name_str + country_str + start_str + end_str

    def get_absolute_url(self):
        return reverse('band-detail', args=[str(self.id)])


class Musician(models.Model):

    INSTRUMENT = [
        ('rhythm guitar', 'rhythm guitar'),
        ('lead guitar', 'lead guitar'),
        ('bass', 'bass'),
        ('drums', 'drums'),
        ('vocals', 'vocals'),
    ]

    ALIVE = [
        (True, 'alive'),
        (False, 'deceased'),
    ]

    name = CharField(max_length=50, default='unknown')
    band = ForeignKey(Band, on_delete=models.SET_NULL, null=True, blank=True)
    instrument = CharField(max_length=50, verbose_name='Primary instrument', default='rhythm guitar', choices=INSTRUMENT)
    born = DateField(null=True, blank=True)
    alive = BooleanField(null=True, blank=True, verbose_name='Alive/Deceased', choices=ALIVE)

    def __str__(self):
        name_str = f'{self.name} '
        band_str = f'({self.band.name}), ' if self.band else '(solo musician), '
        instrument_str = f'{self.instrument}; '
        born_str = f'born {self.born.isoformat()}; ' if self.born else 'birth date unknown; '
        alive_str = 'alive' if self.alive else 'deceased'
        return name_str + band_str + instrument_str + born_str + alive_str

    def get_absolute_url(self):
        return reverse('musician-detail', args=[str(self.id)])

music/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


# def index(request):
#     return HttpResponse('<h1>John Lennon</h1>')
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from music.models import Band, Musician

context_footer = {
    'john': 'John Lennon',
    'life_quote': 'Life is what happens to you while you\'re busy making other plans.'
}


def index(request):
    # return HttpResponse('<h1>John Lennon</h1>')
    context = {
        'john': 'John Lennon',
        'life_quote': 'Life is what happens to you while you\'re busy making other plans.'
    }
    return render(request, 'index.html', context=context)


class IndexView(TemplateView):

    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        # context = {
        #     'john': 'John Lennon',
        #     'life_quote': 'Life is what happens to you while you\'re busy making other plans.'
        # }
        return render(request, 'index.html', context=context_footer)


class BandListView(ListView):

    model = Band
    template_name = 'music/band-list.html'

    def get_queryset(self):
        return Band.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class BandDetailView(DetailView):

    model = Band
    template_name = 'music/band-detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class BandCreateView(CreateView):

    model = Band
    template_name = 'music/band-form.html'
    fields = '__all__'  # fields = ['name', 'country']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class BandUpdateView(UpdateView):

    model = Band
    template_name = 'music/band-form.html'
    fields = '__all__'  # fields = ['name', 'country']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class BandDeleteView(DeleteView):

    model = Band
    template_name = 'music/band-confirm-delete.html'
    success_url = reverse_lazy('band-list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class MusicianListView(ListView):

    model = Musician
    template_name = 'music/musician-list.html'

    def get_queryset(self):
        return Musician.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class MusicianDetailView(DetailView):

    model = Musician
    template_name = 'music/musician-detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class MusicianCreateView(CreateView):

    model = Musician
    template_name = 'music/musician-form.html'
    fields = '__all__'  # fields = ['name', 'country']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class MusicianUpdateView(UpdateView):

    model = Musician
    template_name = 'music/musician-form.html'
    fields = '__all__'  # fields = ['name', 'country']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context


class MusicianDeleteView(DeleteView):

    model = Musician
    template_name = 'music/musician-confirm-delete.html'
    success_url = reverse_lazy('musician-list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(context_footer)
        return context

templates/DTL&HTML.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DTL & HTML</title>
</head>
<body>
<!--
DTL
---

    Extending base template
    -----------------------
    {% extends '<base>.html' %}

    Handling static files
    ---------------------
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <img src="{% static 'images/<<image file name>.<extension>>' %}" alt="">
        example: <img src="{% static 'images/woodstock-iconic.jpg' %}" alt="">

    Blocks
    ------
    Putting everything inside a block into a <div> enables more control over whitespace etc. For example:
    {% block <block_name> %}
        <div class="container-fluid">   {# just <div> is OK as well, the difference is just in some minor indentation #}
            <br>
            <p>...</p>
            <ul>
                <li><strong>XXX: </strong>{{ <var_name (from the corresponding view context)> }}</li>
                ...
            </ul>
        </div>
    {% endblock %}

    Variables
    ---------
    {{ var_name }}
        in list view: <the name of the corresponding class, all lowercase>_list, e.g. {{ performer_list }}
                      {{ object_list }} is a good, universal alternative; works as an alias for each model class
        in detail view: <the name of the corresponding class, all lowercase>, e.g. {{ performer }}
    {{ var_name.field_name }} for accessing a specific object field in a template
    {{ v1.v2_set }} for accessing the list of v2 objects in v1, in case V1 is the ForeignKey for V2
    {{ v1.v2_set.all }} the list of all v2 objects in v1, in case V1 is the ForeignKey for V2

    URLs / Links
    ------------
    {% url '<name of the corresponding view>' <object>.pk %}
        example: {% url 'performer-detail' performer.pk %}
        typical use case: <a href="{% url 'performer-detail' performer.pk %}">{{ performer.name }}</a>

    Forms
    -----
    To render <label>/<input> pairs from the context data as table cells wrapped in <tr> tags:
    <form action="" method="post">
        {% csrf_token %}                used to prevent cross-site request forgery (CSRF);
                                        see https://portswigger.net/web-security/csrf/tokens
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

    To display confirm-delete dialog:
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        &nbsp; &nbsp;                                                           optionally, next to the "Confirm" button
        <a href="{% url 'performer-detail' performer.pk %}">No, keep it</a>     add also the "Cancel" link
    </form>

HTML
----

    HTML forms
    ----------
    Example: entering a team name in a text widget (text field) and pressing the 'OK' button to confirm the action
    <form action="/team_name_url/" method="post">       action: where data goes when 'OK' is pressed ("": the same page)
        <label for="team_name">Enter name: </label>     label: pertains to the text field (see the following <input>)
        <input id="team_name"                           id: the id of the text field/widget in the HTML code
            type="text"                                 type: the sort of widget to be displayed
            name="name_field"                           name: the name of the text field/widget in the HTML code
            value="Default name for team.">             value: the initial value for the field (when first displayed)
        <input type="submit" value="OK">                another widget (a button; for a button, type="submit")
    </form>
-->
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>John Lennon</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">#}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>
</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0">
    <h1>John Lennon</h1>
    <p>Imagine there's no heaven...</p>
</div>

<div class="container" style="margin-top:30px">
    <div class="row">
        <div class="col-sm-4">
            <h3>Links</h3>
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'band-list' %}">Bands</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'musician-list' %}">Musicians</a>
                </li>
            </ul>
            <hr class="d-sm-none">
        </div>
        <div class="col-sm-8">
            <h2>He's a real nowhere man</h2>
            <h5>Sitting in his nowhere land...</h5>
            <br>
{#            <div class="fakeimg">Fake Image</div>#}
            <img src="{% static 'images/lennon1.jpg' %}" alt="">
            <p>People say I'm crazy, doing what I'm doing...</p>
            <br>
            <hr>

            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
    <p><strong>{% block quote %}{% endblock %}</strong>&nbsp;&nbsp; - <em>{% block author %}{% endblock %}</em></p>
</div>

</body>
</html>

templates/base0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>John Lennon</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">#}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>
</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0">
    <h1>John Lennon</h1>
    <p>Imagine there's no heaven...</p>
</div>

<div class="container" style="margin-top:30px">
    <div class="row">
        <div class="col-sm-4">
            <h3>Links</h3>
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Link</a>
                </li>
            </ul>
            <hr class="d-sm-none">
        </div>
        <div class="col-sm-8">
            <h2>He's a real nowhere man</h2>
            <h5>Sitting in his nowhere land...</h5>
            <br>
            <div class="fakeimg">Fake Image</div>
            <p>People say I'm crazy, doing what I'm doing...</p>
        </div>
    </div>
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
    <p><strong>Life is what happens to you while you're busy making other plans.</strong></p>
</div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ john }}
{% endblock %}

{% block quote %}
    {{ life_quote }}
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/band-confirm-delete.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        &nbsp; &nbsp;
        <a href="{% url 'band-detail' band.pk %}">No, keep it</a>
    </form>
    <br>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/band-detail.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    {{ band }}
    {% if band.musician_set.all %}
        <p>Members:</p>
        {% for musician in band.musician_set.all %}
            <li><a href="{% url 'musician-detail' musician.pk %}">{{ musician.name }}</a></li>
        {% endfor %}
        <br>
    {% else %}
        <p></p>
    {% endif %}
    <p>
        <a href="{% url 'band-update' band.pk %}">Update band</a> <br>
        <a href="{% url 'band-delete' band.pk %}">Delete band</a>
    </p>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/band-form.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
    <br>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/band-list.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    {% if band_list %}
        <p>The bands currently registered in the database ({{ band_list.count }}):</p>
        {% for band in band_list %}
            <li><a href="{% url 'band-detail' band.pk %}">{{ band.name }}</a></li>
        {% endfor %}
    {% else %}
        <p>No band is currently registered in the database.</p>
    {% endif %}
    <br>
    <p><a href="{% url 'band-create' %}">Add band</a></p>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/musician-confirm-delete.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        &nbsp; &nbsp;
        <a href="{% url 'musician-detail' musician.pk %}">No, keep it</a>
    </form>
    <br>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/musician-detail.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    {{ musician }}
    <p></p>
    <p>
        <a href="{% url 'musician-update' musician.pk %}">Update musician</a> <br>
        <a href="{% url 'musician-delete' musician.pk %}">Delete musician</a>
    </p>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/musician-form.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
    <br>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}

templates/music/musician-list.html
{% extends 'base.html' %}

{#{% block quote %}#}
{#{% endblock %}#}

{% block author %}
    {{ 'Mick Jagger' }}
{% endblock %}

{% block quote %}
    {{ "It's only rock 'n' roll, but I like it, like it, Yes, I do!" }}
{% endblock %}

{% block content%}
    {% if musician_list %}
        <p>The musicians currently registered in the database ({{ musician_list.count }}):</p>
        {% for musician in musician_list %}
            <li><a href="{% url 'musician-detail' musician.pk %}">{{ musician.name }}</a></li>
        {% endfor %}
    {% else %}
        <p>No musician is currently registered in the database.</p>
    {% endif %}
    <br>
    <p><a href="{% url 'musician-create' %}">Add musician</a></p>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#    <p>index.html</p>#}
{#    <h1>{{ john }}</h1>#}
{#</body>#}
{#</html>#}